const routes = [
    {   
        proyectName: 'Reportaje TV Siria',
        imageRoute: './picture 2.jpg',
        imageModal: './picture 2.jpg',
        link: 'https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Das-FilmBuro.jpg',
        imageLittle: true,
    },
    {   
        proyectName: 'Reportaje Judíos Árabes',
        imageRoute: './picture 3.jpg',
        imageModal: './picture 3.jpg',
        link: ' https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Arabes-Judios.jpg',
        imageLittle: true,
    },
    {   
        proyectName: 'Reportaje Escena artística palestina en ISrael',
        imageRoute: './picture 4.jpg',
        imageModal: './picture 4.jpg',
        link: ' https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Namrud.jpg',
        imageLittle: false,
    },
    {   
        proyectName: ' Pelicula de cine Namrud',
        imageRoute: './picture 5.jpg',
        imageModal: './picture 5.jpg',
        link: ' https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Arte-Palestino.jpg',
        imageLittle: true,
    },
    {   
        proyectName: ' Pelicula de cine Namrud',
        imageRoute: './picture 6.jpg',
        imageModal: './picture 6.jpg',
        link: ' https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Kurdos.jpg',
        imageLittle: true,
    },
    {   
        proyectName: ' Pelicula de cine Namrud',
        imageRoute: './picture 7.jpg',
        imageModal: './picture 7.jpg',
        link: ' https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Educacion-Y-Libertad.jpg',
        imageLittle: true,
    },
    {   
        proyectName: ' Pelicula de cine Namrud',
        imageRoute: './picture 8.jpg',
        imageModal: './picture 8.jpg',
        link: ' https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Carlota-Int.jpg',
        imageLittle: true,
    },
    {   
        proyectName: ' Pelicula de cine Namrud',
        imageRoute: './picture 9.jpg',
        imageModal: './picture 9.jpg',
        link: ' https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Ayotzinapa.jpg',
        imageLittle: true,
    },
    {   
        proyectName: ' Pelicula de cine Namrud',
        imageRoute: './picture 10.jpg',
        imageModal: './picture 10.jpg',
        link: ' https://vimeo.com/384972488',
        linkText: ' www.vimeo.com/384972488',
        desc: 'Rojava y las cicatrices del Estado Islámico',
        imageMobile: './Mobile/Namrud-Prensa.jpg',
        imageLittle: true,
    },
]

export default routes 